[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
  nnoremap <silent> ;b
        \ :<C-u>Denite buffer -split=floating -winrow=1<CR>
  xnoremap <silent> <leader>t
        \ :<C-u>Denite file/rec -split=floating -winrow=1<CR>
  nnoremap <expr> / line('$') > 10000 ? '/' :
  \ ":\<C-u>Denite -buffer-name=search -start-filter line\<CR>"
  nnoremap <expr> n line('$') > 10000 ? 'n' :
  \ ":\<C-u>Denite -buffer-name=search -resume -refresh -no-start-filter\<CR>"
  nnoremap <expr> * line('$') > 10000 ? '*' :
  \ ":\<C-u>DeniteCursorWord -buffer-name=search line\<CR>"
  nnoremap <silent> ;s :<C-u>Denite file/point file/old
        \ -sorters=sorter/sublime
        \ `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`
        \ file file:new<CR>
  nnoremap <silent><expr> tt  &filetype == 'help' ?  "g\<C-]>" :
        \ ":\<C-u>DeniteCursorWord -buffer-name=tag -immediately
        \  tag:include\<CR>"
  nnoremap <silent><expr> tp  &filetype == 'help' ?
        \ ":\<C-u>pop\<CR>" : ":\<C-u>Denite jump\<CR>"
  nnoremap <silent> [Window]n :<C-u>Denite dein<CR>
  nnoremap <silent> [Window]g :<C-u>Denite ghq -default-action=cd<CR>
  nnoremap <silent> ;g :<C-u>Denite -buffer-name=search
        \ -no-empty grep<CR>
  nnoremap <silent> ft :<C-u>Denite filetype<CR>
  nnoremap <silent> <C-t> :<C-u>Denite -buffer-name=deol -split=floating
  \ -cursor-pos=`tabpagenr()-1` deol:zsh<CR>
  nnoremap <silent> <C-k> :<C-u>Denite change jump<CR>
  nnoremap <silent> <C-h> :<C-u>DeniteCursorWord help<CR>
  nnoremap <silent> [Space]gs :<C-u>Denite gitstatus<CR>
  nnoremap <silent> ;;
        \ :<C-u>Denite command command_history<CR>
'''

[plugins.ftplugin]
denite = '''
" Define mappings
nnoremap <silent><buffer><expr> <CR>
\ denite#do_map('do_action')
nnoremap <silent><buffer><expr> a
\ denite#do_map('choose_action')
nnoremap <silent><buffer><expr> d
\ denite#do_map('do_action', 'delete')
nnoremap <silent><buffer><expr> p
\ denite#do_map('do_action', 'preview')
nnoremap <silent><buffer><expr> q
\ denite#do_map('quit')
nnoremap <silent><buffer><expr> '
\ denite#do_map('quick_move')
nnoremap <silent><buffer><expr> i
\ denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> <Space>
\ denite#do_map('toggle_select').'j'
nnoremap <silent><buffer><expr> r
\ denite#do_map('do_action', 'quickfix')
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"

[[plugins]]
repo = 'yous/vim-open-color'

[[plugins]]
repo = 'chase/focuspoint-vim'

[[plugins]]
repo = 'larsbs/vimterial_dark'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'nixprime/cpsm'
build = 'sh -c "PY3=ON ./install.sh"'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

# CSS
# [[plugins]]
# repo = 'hail2u/vim-css3-syntax'
# on_ft = ['css', 'scss', 'sass']

# Javascript
[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript','typescript','javascript.jsx','typescript.tsx']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript','typescript.tsx']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript','typescript','javascript.jsx','typescript.tsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['javascript','typescript','javascript.jsx','typescript.tsx']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['javascript','typescript','javascript.jsx','typescript.tsx']

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
on_ft = 'diff'

[[plugins]]
repo = 'thinca/vim-ft-vim_fold'
on_ft = 'vim'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'
on_ft = 'help'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = 'ruby'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'Dockerfile'
