[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
hook_add = '''
  let g:NERDTreeMinimalUI=1
  map <C-c> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'rking/ag.vim'
on_cmd = 'Ag'

# Rust
[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
  let $RUST_SRC_PATH = expand('~/src/rust/src')
  let g:racer_experimental_completer = 1
'''

# [[plugins]]
# repo = 'kana/vim-niceblock'
# on_map = [['x', '<Plug>']]
# hook_add = '''
#   xmap I  <Plug>(niceblock-I)
#   xmap A  <Plug>(niceblock-A)
# '''
# 
# [[plugins]]
# repo = 'vim-jp/vital.vim'

# [[plugins]]
# repo = 'thinca/vim-qfreplace'
# on_ft = 'quickfix'
# hook_source = '''
#   autocmd MyAutoCmd FileType qf nnoremap <buffer> r :<C-u>Qfreplace<CR>
# '''


# [[plugins]]
# repo = 'rhysd/accelerated-jk'
# on_map = [['n', '<Plug>']]
# hook_add = '''
#   nmap <silent>j <Plug>(accelerated_jk_gj)
#   nmap <silent>k <Plug>(accelerated_jk_gk)
# '''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'


[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'tpope/vim-rails'
